[versions]
agp = "8.2.1"
kotlin = "1.9.21"
coreKtx = "1.12.0"
activity = "1.8.2"
koin = "3.5.3"
koinCompose = "1.1.2"
gson = "2.10.1"
okhttp = "4.12.0"
retrofit = "2.9.0"
compose = "1.5.4"
composeBom = "2023.10.01"
navigationCompose = "2.7.6"
playServicesLocation = "21.0.1"
androidxComposeMaterial3 = "1.1.2"
car = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koinCompose" }
koin-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation", version.ref = "koin" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logginginterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

androidx-car = { group = "androidx.car.app", name = "app", version.ref = "car" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
compose = ["androidx-navigation-compose", "androidx-compose-material3", "androidx-compose-material",
    "androidx-compose-ui", "androidx-compose-bom", "androidx-compose-activity"]
koin = ["koin-android", "koin-compose", "koin-navigation"]
network = ["gson", "retrofit", "retrofit-gson", "okhttp-logginginterceptor"]